-- MySQL Script generated by MySQL Workbench
-- Mon Mar  2 18:28:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendaw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendaw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendaw` DEFAULT CHARACTER SET utf8 ;
USE `tiendaw` ;

-- -----------------------------------------------------
-- Table `tiendaw`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaw`.`articulos` (
  `id_articulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NULL,
  `precio` INT NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_articulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaw`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaw`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(100) NOT NULL,
  `preciototal` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `esta_pagado` INT NOT NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `tiendaw`.`articulosxpedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaw`.`articulosxpedido` (
  `id_articulo` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_articulo`, `id_pedido`),
  INDEX `fk_articulos_has_pedidos_pedidos1_idx` (`id_pedido` ASC),
  INDEX `fk_articulos_has_pedidos_articulos_idx` (`id_articulo` ASC),
  CONSTRAINT `fk_articulos_has_pedidos_articulos`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `tiendaw`.`articulos` (`id_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_has_pedidos_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `tiendaw`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaw`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaw`.`carro` (
  `usuario` VARCHAR(200) NOT NULL,
  `cantidad` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  INDEX `fk_carro_articulos1_idx` (`id_articulo` ASC),
  CONSTRAINT `fk_carro_articulos1`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `tiendaw`.`articulos` (`id_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- -----------------------------------------------------
-- insercion articulos
-- -----------------------------------------------------

INSERT INTO `articulos` (`id_articulo`, `nombre`, `descripcion`, `precio`, `imagen`) VALUES (NULL, 'Bicicleta BTT 26', 'Bicicleta 6 velocidades con freno V Brake, triple plato y horquilla rigida', '11820', 'bici1.jpg'), (NULL, 'Moma Bikes Bicicleta Montaña HIT 26', 'Cambio Shimano TZ-50 21 velocidades, doble freno disco, full suspension', '24035', 'bici2.jpg'), (NULL, 'Moma Bikes City Classic 26', 'Bicicleta Paseo, Aluminio , Cambio Shimano TZ-50 18 vel., Blanco', '19999', 'bici3.jpg'), (NULL, 'Moma Bikes Mtb29 Peak M', 'Bicicleta de Montaña, Frenos de Disco hidraulicos, 27V, Unisex Adulto, Verde', '34480', 'bici4.jpg'), (NULL, 'Moma Bikes Top Class 24', 'Bicicleta Plegable Urbana, Cambio Shimano TZ-50 6 vel, Ruedas de 24″ con llantas de aluminio, color Negro', '19990', 'bici5.jpg'), (NULL, 'F.lli Schiano Voyager', 'Bicicleta Trekking, Men\'s, Negro-Azul, 6 velocidades', '14500', 'bici6.jpg')
